### ISSUE TITLE
[Link Quebrado na Tradução]:  Castlevania - Harmony of Dissonance (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#10]
### Título do Tradução

Castlevania - Harmony of Dissonance (Trans-Center)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link do patch, para facilitar: https://www.romhacking.net/translations/5178/

**Comment by hansbonini** [comment]
Resolvido em #36
