### ISSUE TITLE
[Link Quebrado na Tradução]:  Metroid Fusion (Tradu-Roms, Trans-Center e PO.B.R.E.)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#12]
### Título do Tradução

Metroid Fusion (Tradu-Roms, Trans-Center e PO.B.R.E.)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link, para facilitar: https://www.romhacking.net/translations/5156/

**Comment by hansbonini** [comment]
Resolvido em #36
