### ISSUE TITLE
[Link Quebrado na Tradução]:  Metroid - Zero Mission (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#13]
### Título do Tradução

Metroid - Zero Mission (Trans-Center)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5151/

**Comment by hansbonini** [comment]
Resolvido em #36
