### ISSUE TITLE
[Link Quebrado na Tradução]:  Megaman Zero (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#14]
### Título do Tradução

Megaman Zero (Trans-Center)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link do patch, pra facilitar: https://www.romhacking.net/translations/5137/

**Comment by hansbonini** [comment]
Resolvido em #36
