### ISSUE TITLE
[Link Quebrado na Tradução]:  The Legend of Zelda - The Minish Cap (Trans-Center, PO.B.R.E. e Projeto BR)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#20]
### Título do Tradução

The Legend of Zelda - The Minish Cap (Trans-Center, PO.B.R.E. e Projeto BR)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Essa tradução foi revisada ano passado e lançada em janeiro com centenas de correções e uma mudança na tela-título (Gorro Minimizador). Upei ele no rh.net como uma atualização da versão original de 2008. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5249/

**Comment by hansbonini** [comment]
Resolvido em #36
