### ISSUE TITLE
[Link Quebrado na Tradução]:  The Legend of Zelda: A Link to the Past & Four Swords (Hyrule Legends, Monkey's Traduções e Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#21]
### Título do Tradução

The Legend of Zelda: A Link to the Past & Four Swords (Hyrule Legends, Monkey's Traduções e Trans-Center)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Essa tradução foi atualizada em janeiro de 2023 com a inclusão do jogo multiplayer Four Swords (Quatro Espadas). Upei ele no rh.net como uma atualização da versão original de 2013. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5277/

**Comment by hansbonini** [comment]
Resolvido em #36
