### ISSUE TITLE
[Link Quebrado na Tradução]:  Castlevania - Dawn of Sorrow (Hyllian)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#22]
### Título do Tradução

Castlevania - Dawn of Sorrow (Hyllian)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia cadastrado a tradução no rh.net uns anos atrás. Aqui o link do patch, pra facilitar: https://www.romhacking.net/translations/5315/

**Comment by hansbonini** [comment]
Resolvido em #36

**Comment by hansbonini** [comment]
Corrigido em #48
