### ISSUE TITLE
[Link Quebrado na Tradução]:  Castlevania - Portrait of Ruin (Monkey's Traduções e Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#23]
### Título do Tradução

Castlevania - Portrait of Ruin (Monkey's Traduções e Trans-Center)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link do patch, pra facilitar: https://www.romhacking.net/translations/5316/

**Comment by hansbonini** [comment]
Resolvido em #36
