### ISSUE TITLE
[Link Quebrado na Tradução]:  Castlevania - Order of Ecclesia (POBRE e Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#24]
### Título do Tradução

Castlevania - Order of Ecclesia (POBRE e Trans-Center)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link do patch, pra facilitar: https://www.romhacking.net/translations/5317/

**Comment by hansbonini** [comment]
Resolvido em #36

**Comment by hansbonini** [comment]
Corrigido em #48
