### ISSUE TITLE
[Link Quebrado na Tradução]:  Rock Man ZX (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#25]
### Título do Tradução

Rock Man ZX (Trans-Center)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5181/

**Comment by hansbonini** [comment]
Resolvido em #36

**Comment by hansbonini** [comment]
Corrigido em #48
