### ISSUE TITLE
[Link Quebrado na Tradução]:  Mega Man ZX Advent (Trans-Center e Monkey's Traduções)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#26]
### Título do Tradução

Mega Man ZX Advent (Trans-Center e Monkey's Traduções)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5233/

**Comment by hansbonini** [comment]
Resolvido em #36

**Comment by hansbonini** [comment]
Corrigido em #48
