### ISSUE TITLE
[Link Quebrado na Tradução]:  The Legend of Zelda - Phantom Hourglass (Projeto BR, Trans-Center, Hyrule Legends e Monkey's Traduções)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#27]
### Título do Tradução

The Legend of Zelda - Phantom Hourglass (Projeto BR, Trans-Center, Hyrule Legends e Monkey's Traduções)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link, pra facilitar: https://www.romhacking.net/translations/5265/

**Comment by hansbonini** [comment]
Resolvido em #36

**Comment by hansbonini** [comment]
Corrigido em #48
