### ISSUE TITLE
[Link Quebrado na Tradução]:  Metroid Prime Hunters (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#28]
### Título do Tradução

Metroid Prime Hunters (Trans-Center)

### Sistema

Nintendo DS

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a tradução no rh.net uns anos atrás. Aqui o link do patch, pra facilitar: https://www.romhacking.net/translations/5264/

**Comment by hansbonini** [comment]
Corrigido em #48
