### ISSUE TITLE
[Corrigir Tradução]: Tetris (Tengen)

### ISSUE THREAD

**Issue by ajkmetiuk** [romhackersbr/romhackersbr-db#33]
### Título do Tradução

Tetris (Tengen) (ajkmetiuk)

### Sistema

NES

### Plataforma

Console

### Titulo do Jogo

Tetris (Tengen)

### Categoria do Jogo

Quebra Cabeças

### Numero de Jogadores

2

### Desenvolvedora do Jogo

Tengen

### Distribuidora do Jogo

Tengen

### Data de Lançamento do Jogo

17/05/1989

### Autor(es) da Tradução

ajkmetiuk

### Grupo(s) da Tradução

Nenhum

### Site da Tradução

Nenhum

### Versão da Tradução

1.1

### Data de Lançamento da Tradução

04/08/2018

### Tipo de Patch

IPS

### Progresso da Tradução

100%

### Imagens da Tradução

```markdown
https://cdn.discordapp.com/attachments/1083409896344657951/1112843381333303366/1.png
https://cdn.discordapp.com/attachments/1083409896344657951/1112843396869009553/2.png
https://cdn.discordapp.com/attachments/1083409896344657951/1112843409640656947/3.png
https://cdn.discordapp.com/attachments/1083409896344657951/1112843420352909342/4.png
https://cdn.discordapp.com/attachments/1083409896344657951/1112843433351061594/5.png
```

### Link para o patch da tradução

cdn.discordapp.com/attachments/1083409896344657951/1112844189135286414/Tetris_BR_v1_1.7z

### Descrição da Tradução

```markdown
Segundo o autor da tradução, todos os textos estão traduzidos e acentuados (exceto a tela de título na ROM Tetris (Tengen) [p1][!].nes), e os gráficos foram editados. ATENÇÃO:Esta tradução deve ser aplicada na ROM original Tetris (Tengen) [p2][!].nes, com CRC32 C107E000, ou na ROM original Tetris (Tengen) [p1].nes, com CRC32 A66CD1DC. NOVIDADES DA VERSÃO 1.1: Editado os gráficos para remover as abreviações.
```

**Comment by hansbonini** [comment]
Corrigido em #37
