### ISSUE TITLE
[Link Quebrado na Tradução]:  The Lord of The Rings - The Fellowship of The Ring (Evil Darkness)

### ISSUE THREAD

**Issue by sombramanchada** [romhackersbr/romhackersbr-db#4]
### Título do Tradução

The Lord of The Rings - The Fellowship of The Ring (Evil Darkness)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by hansbonini** [comment]
Encaminhando para correção

**Comment by hansbonini** [comment]
Corrigido
