### ISSUE TITLE
[Link Quebrado na Tradução]:  Megaman Battle Network (Marcelo Sahgo)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#8]
### Título do Tradução

Megaman Battle Network (Marcelo Sahgo)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Por sorte, havia conseguido o link do patch um dia desses com o felix (gamer_boy), e upei ele no rh.net: https://www.romhacking.net/translations/6842/

Podemos opcionalmente só baixar do rh.net e upar no site.

**Comment by hansbonini** [comment]
Os arquivos não estavam perdidos, todos estão presentes no cdn. Só faltava linkar.
Resolvido em #36
