### ISSUE TITLE
[Link Quebrado na Tradução]:  Castlevania - Aria of Sorrow (Trans-Center)

### ISSUE THREAD

**Issue by leomontenegro6** [romhackersbr/romhackersbr-db#9]
### Título do Tradução

Castlevania - Aria of Sorrow (Trans-Center)

### Sistema

Game Boy Advance

### Plataforma

Portátil

**Comment by leomontenegro6** [comment]
Havia upado a versão mais recente da tradução no rh.net uns anos atrás. Aqui o link, para facilitar: https://www.romhacking.net/translations/5167/

**Comment by hansbonini** [comment]
Resolvido em #36
